# site settings
title: Jacopo Parvizi
subtitle: Data Scientist
permalink: none
email: jacopo.parvizi@gmail.com
description: I am a Data Scientist with a strong passion for data science.<br/>I have authored several publications using<br/>statistical learning methods to solve complex problems.<br/> <br/> I have worked in both the public and private sector,<br/>developing and implementing software and performing analyses,<br/>turning numbers into data-driven insights.
baseurl: '/'# the subpath of your site, e.g. /blog
url: https://jacopoparvizi.com # the base hostname & protocol for your site
author: "Jacopo Parvizi"
street_address: Jolly 09:35
city: BlackRock City
state: NV
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mottiden
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/jacopoparvizi
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mottiden

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: 

# build settings
markdown: kramdown

sass:
  style: compressed
